---
abstract: 'Use System-wide Hotkeys independently'
author:
  - 'Tarek Unger <tu2@gmx.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-GlobalHotkey
no_index:
  directory:
    - t
    - inc
requires:
  Thread::Cancel: 0
  threads: 0
  threads::shared: 0
version: 0.01_1
